### DISCUSSION TITLE
Creating scrape jobs vs. adding annotations to Kubernetes

### DISCUSSION THREAD

**Discussion by christian-kreuzberger-dtx** [keptn-contrib/prometheus-service#242] [Ideas]
Right now prometheus-service works by creating scrape jobs for every stage and every possible candidate a service could have, e.g.:

https://github.com/keptn-contrib/prometheus-service/blob/44488abcea2cd4ef4323e288dfc6fe3833099f93/eventhandling/configureEvent.go#L250-L259

I think this behaviour could be improved such that every service that should be monitored needs to have the correct [annotations](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#scraping-pod-metrics-via-annotations) set, e.g.:

```yaml
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
```

This would allow us to remove the code for creating scrape jobs in prometheus-service.

I'm not sure which behaviour would be considered best practice, so please let me know via answering or via voting :+1: if you favor this change, or :-1: if you are against this change.
