### ISSUE TITLE
Allow labels to be used as placeholders

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/prometheus-service#259]
As a user, I want to use `labels` to help identify workloads for evaluations, e.g.:

```bash
keptn trigger evaluation --project=<PROJECT> --service=<SERVICE> --stage=<STAGE> --labels version=1.2.3,owner=JohnDoe,testrunid=10
```
or using the API
```json
{
  "source": "keptn-cli",
  "specversion": "1.0",
  "type": "sh.keptn.event.<STAGE>.evaluation.triggered",
  "contenttype": "application/json",
  "data": {
    "evaluation": {
      "start": "2020-09-01T08:31:06Z",
      "end": "2020-09-01T08:36:06Z"
    },
    "labels": {
      "version": "1.2.3",
      "owner": "JohnDoe",
      "testrunid": "10"
    },
    "project": "<PROJECT>",
    "service": "<SERVICE>",
    "stage": "<STAGE>"
  }
}

```

This will then lead to keptn/lighthouse-service to send the following `get-sli.triggered` event:
```yaml
{
  "data": {
    "deployment": "",
    "get-sli": {
      "end": "2022-02-02T07:59:21.232Z",
      "sliProvider": "prometheus",
      "start": "2022-02-02T07:57:21.232Z"
    },
    "labels": {
      "version": "1.2.3",
      "owner": "JohnDoe",
      "testrunid": "10"
    },
    "project": "<PROJECT>",
    "service": "<SERVICE>",
    "stage": "<STAGE>"
  },
  "id": "e0cd1abb-aa32-4b23-80be-bab5c8605f0e",
  "source": "lighthouse-service",
  "specversion": "1.0",
  "time": "2022-02-02T07:59:21.266Z",
  "type": "sh.keptn.event.get-sli.triggered",
  "shkeptncontext": "...",
  "shkeptnspecversion": "0.2.3"
}
```

In prometheus, the SLI configuration can then reference labels using `$LABEL.<labelname>`, e.g., `$LABEL.testrunid`.

**Full SLI Example: prometheus/sli.yaml**

```yaml
---
spec_version: '1.0'
indicators:
  http_requests_total_sucess: http_requests_total{status="success",job="$SERVICE-$PROJECT-$STAGE-$LABEL.testrunid"}
```

**slo.yaml**
```yaml
---
spec_version: '0.1.0'
comparison:
  compare_with: "single_result"
  include_result_with_score: "pass"
  aggregate_function: avg
objectives:
  - sli: http_requests_total_sucess
    displayName: "HTTP Response Total"

```

# Definition of Done

- [ ] SLI [replace query params](https://github.com/keptn-contrib/prometheus-service/blob/a41d9c0893974a884ae94f8296b5944c84a6f43f/eventhandling/configureEvent.go#L482-L498) function also replaces `$LABELS.labelname` with the value of the label
- [ ] [Documentation for custom SLI queries](https://github.com/keptn-contrib/prometheus-service/blob/master/README.md#custom-sli-queries) updated
