### ISSUE TITLE
Use keptn create secret for creating secrets instead of Kubernetes

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/prometheus-service#274]
When ["Using an external prometheus source" as an SLI provider](https://github.com/keptn-contrib/prometheus-service#using-an-external-prometheus-instance), a user needs to create a secret using Kubernetes:
```bash
kubectl create secret -n keptn generic prometheus-credentials-<project> --from-file=prometheus-credentials=./mock_secret.yaml
```

This should be changed such that a user does no longer need `kubectl` and Kubernetes API Access, but using `keptn`:

**Old Way**
```yaml
user: test
password: test
url: http://prometheus-service.monitoring.svc.cluster.local
```

```bash
kubectl create secret -n keptn generic prometheus-credentials-<project> --from-file=prometheus-credentials=./secrets.yaml
```

**New Way**
```bash
PROMETHEUS_USER=test
PROMETHEUS_PASSWORD=test-password
PROMETHEUS_URL=http://prometheus-server.monitoring.svc.cluster.local

keptn create secret prometheus-credentials-<project> --scope="keptn-prometheus-service" --from-literal="PROMETHEUS_USER=$PROMETHEUS_USER" --from-literal="PROMETHEUS_PASSWORD=$PROMETHEUS_PASSWORD" --from-literal="PROMETHEUS_URL=$PROMETHEUS_URL"
```

The secret created will still be the same name, but it's no longer a yaml file, therefore we need to adapt code:
https://github.com/keptn-contrib/prometheus-service/blob/827a4ccfae25a724328e19d3001ef1ef80825414/eventhandling/getSliEvent.go#L189-L190

In addition, we need to add a new scope to Keptn Core secret-service here:
https://github.com/keptn/keptn/blob/bd57d168ba49064738204c5e0bce8086be994c00/installer/manifests/keptn/charts/control-plane/templates/secret-service.yaml#L12-L29

The scope will look like this:
```
      keptn-prometheus-service: # <-- Kubernetes role name
        Capabilities:
          keptn-prometheus-svc-read:
            Permissions:
              - get
```

# Definition of Done

- [ ] README.md updated
- [x] New scope added to Keptn Core repo
- [ ] Implementation of prometheus-service updated and tested for the get-sli use-case
