### ISSUE TITLE
RFE: Quality gates for existing CI/CD + monitoring solutions

### ISSUE THREAD

**Issue by aemorales2** [keptn-contrib/prometheus-service#291]
I would like to use keptn to evaluate SLOs in an infrastructure with existing multistage CI/CD and existing monitoring with prometheus. Ideally, this "standalone quality gate" would be able to be configured to use the existing scrape jobs in prometheus for SLO evaluations given we can retrieve the results with an API call to use in our CI/CD process.

**Comment by christian-kreuzberger-dtx** [comment]
This is already possible. You need to setup Prometheus to monitor your data / endpoints / ... as you need it.

Afterwards, you can select which metrics you want to fetch by specifying the metric, job, and other identifiers (basically this is your Prometheus metric expression) in your `prometheus/sli.yaml`, e.g.:

**prometheus/sli.yaml**
```yaml
---
spec_version: '1.0'
indicators:
  your_sli_name: histogram_quantile(0.5, sum by(le) (rate(whatever_metric_you_want{job="name_of_your_scrape_job"}[$DURATION_SECONDS])))

```
Setting `$DURATION_SECONDS` is optional, you can specify a static value like "5m" as well. `$DURATION_SECONDS` is automatically determined by the `start` and `end` time specified in the `evaluation.triggered` event (or as presented to `keptn trigger evaluation` CLI command).


Hope this helps,
Christian
